// lib/albums.ts

export type Album = {
  id: number;
  title: string;
  artist: string;
  year: number;
  coverUrl: string;
};

export const albums: Album[] = [
  {
    id: 1,
    title: "Debug Album One",
    artist: "Professor Sparks",
    year: 2024,
    coverUrl: "https://images.pexels.com/photos/164745/pexels-photo-164745.jpeg",
  },
  {
    id: 2,
    title: "Debug Album Two",
    artist: "Arsenije Brajovic",
    year: 2025,
    coverUrl: "https://images.pexels.com/photos/374703/pexels-photo-374703.jpeg",
  },
  {
    id: 3,
    title: "Midnight Coding Sessions",
    artist: "Lo-Fi Compiler",
    year: 2023,
    coverUrl: "https://images.pexels.com/photos/1647458/pexels-photo-1647458.jpeg",
  },
  {
    id: 4,
    title: "Bug Fix Bangers",
    artist: "Stack Trace",
    year: 2022,
    coverUrl: "https://images.pexels.com/photos/1037992/pexels-photo-1037992.jpeg",
  },
  {
    id: 5,
    title: "Finals Week Playlist",
    artist: "GCU Labs",
    year: 2021,
    coverUrl: "https://images.pexels.com/photos/164716/pexels-photo-164716.jpeg",
  },
  {
    id: 6,
    title: "Coffee Shop Beats",
    artist: "Campus Café",
    year: 2020,
    coverUrl: "https://images.pexels.com/photos/63703/pexels-photo-63703.jpeg",
  },
  {
    id: 7,
    title: "Desert Night Drives",
    artist: "Phoenix Highways",
    year: 2019,
    coverUrl: "https://images.pexels.com/photos/248747/pexels-photo-248747.jpeg",
  },
  {
    id: 8,
    title: "Workout Warmups",
    artist: "Gym Floor",
    year: 2022,
    coverUrl: "https://images.pexels.com/photos/136869/pexels-photo-136869.jpeg",
  },
  {
    id: 9,
    title: "Lo-Fi Study Hall",
    artist: "Dorm Room 404",
    year: 2023,
    coverUrl: "https://images.pexels.com/photos/1181675/pexels-photo-1181675.jpeg",
  },
  {
    id: 10,
    title: "Sunset on Campus",
    artist: "Parking Garage Views",
    year: 2021,
    coverUrl: "https://images.pexels.com/photos/799443/pexels-photo-799443.jpeg",
  },
  {
    id: 11,
    title: "Late Night Debugging",
    artist: "Console Logger",
    year: 2024,
    coverUrl: "https://images.pexels.com/photos/1181671/pexels-photo-1181671.jpeg",
  },
  {
    id: 12,
    title: "Chill Lab Hours",
    artist: "CS Building",
    year: 2020,
    coverUrl: "https://images.pexels.com/photos/577585/pexels-photo-577585.jpeg",
  },
  {
    id: 13,
    title: "Morning Commute",
    artist: "City Bus 17",
    year: 2018,
    coverUrl: "https://images.pexels.com/photos/187938/pexels-photo-187938.jpeg",
  },
  {
    id: 14,
    title: "Weekend Reset",
    artist: "Laundry & Groceries",
    year: 2019,
    coverUrl: "https://images.pexels.com/photos/37347/records-vintage-old-music.jpg",
  },
  {
    id: 15,
    title: "Pre-Exam Nerves",
    artist: "Library Stairs",
    year: 2022,
    coverUrl: "https://images.pexels.com/photos/374727/pexels-photo-374727.jpeg",
  },
  {
    id: 16,
    title: "Boxing Gym Energy",
    artist: "Heavy Bag",
    year: 2023,
    coverUrl: "https://images.pexels.com/photos/4761667/pexels-photo-4761667.jpeg",
  },
  {
    id: 17,
    title: "Late Night Walks",
    artist: "Campus Lights",
    year: 2021,
    coverUrl: "https://images.pexels.com/photos/1105666/pexels-photo-1105666.jpeg",
  },
  {
    id: 18,
    title: "Cloudy Afternoon",
    artist: "Dorm Window",
    year: 2020,
    coverUrl: "https://images.pexels.com/photos/462162/pexels-photo-462162.jpeg",
  },
  {
    id: 19,
    title: "Debugging Victory",
    artist: "Green Checkmark",
    year: 2024,
    coverUrl: "https://images.pexels.com/photos/1181467/pexels-photo-1181467.jpeg",
  },
  {
    id: 20,
    title: "Project All-Nighter",
    artist: "Blue Light Glasses",
    year: 2024,
    coverUrl: "https://images.pexels.com/photos/577585/pexels-photo-577585.jpeg",
  },
  {
    id: 21,
    title: "Dorm Room Chill",
    artist: "Room 312",
    year: 2019,
    coverUrl: "https://images.pexels.com/photos/935785/pexels-photo-935785.jpeg",
  },
  {
    id: 22,
    title: "Weekend Vibes",
    artist: "City Lights",
    year: 2020,
    coverUrl: "https://images.pexels.com/photos/799443/pexels-photo-799443.jpeg",
  },
  {
    id: 23,
    title: "Coding with Coffee",
    artist: "Double Espresso",
    year: 2023,
    coverUrl: "https://images.pexels.com/photos/302899/pexels-photo-302899.jpeg",
  },
  {
    id: 24,
    title: "Morning Run",
    artist: "Track Lane 4",
    year: 2021,
    coverUrl: "https://images.pexels.com/photos/2402777/pexels-photo-2402777.jpeg",
  },
  {
    id: 25,
    title: "Dorm Kitchen Sessions",
    artist: "Microwave Gourmet",
    year: 2022,
    coverUrl: "https://images.pexels.com/photos/1098618/pexels-photo-1098618.jpeg",
  },
  {
    id: 26,
    title: "Game Night Hype",
    artist: "Lobby Squad",
    year: 2021,
    coverUrl: "https://images.pexels.com/photos/1293261/pexels-photo-1293261.jpeg",
  },
  {
    id: 27,
    title: "Sunday Reset",
    artist: "Clean Desk",
    year: 2020,
    coverUrl: "https://images.pexels.com/photos/374720/pexels-photo-374720.jpeg",
  },
  {
    id: 28,
    title: "Sunrise on Campus",
    artist: "East Lot",
    year: 2018,
    coverUrl: "https://images.pexels.com/photos/46253/pexels-photo-46253.jpeg",
  },
  {
    id: 29,
    title: "Lo-Fi Elevator",
    artist: "Floor Seven",
    year: 2019,
    coverUrl: "https://images.pexels.com/photos/132340/pexels-photo-132340.jpeg",
  },
  {
    id: 30,
    title: "End of Semester",
    artist: "Final Grade",
    year: 2025,
    coverUrl: "https://images.pexels.com/photos/590493/pexels-photo-590493.jpeg",
  },
];
